### Import the sample data as a Quilt package
This dataset is daily sales of Noci, a neighborhood gelato shop in Mill Valley, from approximately 2007-2012.

In [1]:
from quilt.data.kmoore import nocisales

### Access the sample data as a SQLite Database

In [2]:
import sqlalchemy as sa
eng = sa.create_engine("sqlite:///%s" % nocisales.sqlite())
for row in eng.execute("select * from NociGelato"):        
    print(row)

('2012-03-16 00:00:00.000000', 'Friday', 435.65)
('2011-12-31 00:00:00.000000', 'Saturday', 239.35)
('2012-03-13 00:00:00.000000', 'Tuesday', 137.25)
('2012-02-02 00:00:00.000000', 'Thursday', 531.35)
('2011-10-25 00:00:00.000000', 'Tuesday', 428.6)
('2011-01-26 00:00:00.000000', 'Wednesday', 509.25)
('2011-10-26 00:00:00.000000', 'Wednesday', 620.1)
('2011-01-25 00:00:00.000000', 'Tuesday', 348.0)
('2011-10-23 00:00:00.000000', 'Sunday', 1043.15)
('2011-01-28 00:00:00.000000', 'Friday', 776.1)
('2011-10-24 00:00:00.000000', 'Monday', 270.0)
('2011-10-29 00:00:00.000000', 'Saturday', 1057.7)
('2011-10-30 00:00:00.000000', 'Sunday', 875.05)
('2011-01-27 00:00:00.000000', 'Thursday', 458.85)
('2011-10-27 00:00:00.000000', 'Thursday', 469.35)
('2011-10-28 00:00:00.000000', 'Friday', 758.65)
('2012-02-08 00:00:00.000000', 'Wednesday', 404.25)
('2011-01-30 00:00:00.000000', 'Sunday', 396.35)
('2007-10-08 00:00:00.000000', 'Monday', 495.25)
('2012-02-07 00:00:00.000000', 'Tuesday', 273.25)
('2007-10-09 00:00:00.000000', 'Tuesday', 210.0)
('2011-10-31 00:00:00.000000', 'Monday', 233.45)
('2011-01-29 00:00:00.000000', 'Saturday', 628.8)
('2007-10-06 00:00:00.000000', 'Saturday', 1118.75)
('2011-11-01 00:00:00.000000', 'Tuesday', 302.2)
('2007-10-07 00:00:00.000000', 'Sunday', 941.75)
('2011-02-01 00:00:00.000000', 'Tuesday', 513.6)
('2012-02-04 00:00:00.000000', 'Saturday', 992.15)
('2007-10-04 00:00:00.000000', 'Thursday', 351.5)
('2011-01-31 00:00:00.000000', 'Monday', 306.75)
('2011-12-12 00:00:00.000000', 'Monday', 230.2)
('2012-02-06 00:00:00.000000', 'Monday', 195.0)
('2012-02-05 00:00:00.000000', 'Sunday', 479.85)
('2011-12-30 00:00:00.000000', 'Friday', 401.15)
('2007-10-05 00:00:00.000000', 'Friday', 803.75)
('2011-02-03 00:00:00.000000', 'Thursday', 585.55)
('2011-12-11 00:00:00.000000', 'Sunday', 256.95)
('2007-10-02 00:00:00.000000', 'Tuesday', 547.5)
('2011-02-02 00:00:00.000000', 'Wednesday', 451.1)
('2012-02-01 00:00:00.000000', 'Wednesday', 428.9)
('2007-10-03 00:00:00.000000', 'Wednesday', 580.25)
('2011-07-16 00:00:00.000000', 'Saturday', 1191.8)
('2012-03-17 00:00:00.000000', 'Saturday', 636.35)
('2011-07-15 00:00:00.000000', 'Friday', 888.35)
('2007-10-10 00:00:00.000000', 'Wednesday', 398.75)
('2011-07-22 00:00:00.000000', 'Friday', 1083.55)
('2007-10-11 00:00:00.000000', 'Thursday', 376.5)
('2012-01-12 00:00:00.000000', 'Thursday', 457.65)
('2007-12-21 00:00:00.000000', 'Friday', 444.6)
('2011-07-21 00:00:00.000000', 'Thursday', 840.5)
('2012-01-13 00:00:00.000000', 'Friday', 639.0)
('2011-07-20 00:00:00.000000', 'Wednesday', 1210.35)
('2007-12-20 00:00:00.000000', 'Thursday', 453.2)
('2011-07-19 00:00:00.000000', 'Tuesday', 1065.55)
('2011-05-13 00:00:00.000000', 'Friday', 773.15)
('2011-05-14 00:00:00.000000', 'Saturday', 823.7)
('2011-05-11 00:00:00.000000', 'Wednesday', 595.35)
('2011-05-12 00:00:00.000000', 'Thursday', 628.05)
('2011-05-09 00:00:00.000000', 'Monday', 648.2)
('2011-12-06 00:00:00.000000', 'Tuesday', 178.5)
('2011-05-10 00:00:00.000000', 'Tuesday', 659.9)
('2011-05-07 00:00:00.000000', 'Saturday', 1080.05)
('2011-05-08 00:00:00.000000', 'Sunday', 825.7)
('2007-12-17 00:00:00.000000', 'Monday', 331.75)
('2011-12-05 00:00:00.000000', 'Monday', 347.15)
('2011-05-05 00:00:00.000000', 'Thursday', 782.6)
('2011-05-06 00:00:00.000000', 'Friday', 885.0)
('2010-11-23 00:00:00.000000', 'Tuesday', 495.05)
('2007-12-16 00:00:00.000000', 'Sunday', 472.5)
('2011-10-14 00:00:00.000000', 'Friday', 1165.65)
('2010-11-22 00:00:00.000000', 'Monday', 289.1)
('2010-11-19 00:00:00.000000', 'Friday', 310.0)
('2010-11-18 00:00:00.000000', 'Thursday', 409.15)
('2007-12-19 00:00:00.000000', 'Wednesday', 308.25)
('2010-11-21 00:00:00.000000', 'Sunday', 419.35)
('2011-10-13 00:00:00.000000', 'Thursday', 649.65)
('2010-11-20 00:00:00.000000', 'Saturday', 394.1)
('2007-12-18 00:00:00.000000', 'Tuesday', 388.5)
('2007-12-13 00:00:00.000000', 'Thursday', 330.9)
('2007-12-12 00:00:00.000000', 'Wednesday', 297.15)
('2007-12-15 00:00:00.000000', 'Saturday', 419.7)
('2010-11-15 00:00:00.000000', 'Monday', 423.3)
('2007-12-14 00:00:00.000000', 'Friday', 279.5)
('2008-09-04 00:00:00.000000', 'Thursday', 966.0)
('2011-10-16 00:00:00.000000', 'Sunday', 744.1)
('2008-09-05 00:00:00.000000', 'Friday', 1434.75)
('2008-09-06 00:00:00.000000', 'Saturday', 1442.0)
('2008-09-07 00:00:00.000000', 'Sunday', 695.0)
('2008-08-31 00:00:00.000000', 'Sunday', 1252.5)
('2010-11-14 00:00:00.000000', 'Sunday', 782.8)
('2011-10-15 00:00:00.000000', 'Saturday', 1045.45)
('2010-11-17 00:00:00.000000', 'Wednesday', 476.45)
('2008-09-01 00:00:00.000000', 'Monday', 1213.0)
('2008-09-02 00:00:00.000000', 'Tuesday', 789.25)
('2011-10-18 00:00:00.000000', 'Tuesday', 382.1)
('2010-11-16 00:00:00.000000', 'Tuesday', 301.85)
('2011-10-17 00:00:00.000000', 'Monday', 688.55)
('2008-06-13 00:00:00.000000', 'Friday', 995.9)
('2010-04-17 00:00:00.000000', 'Saturday', 1034.1)
('2011-10-20 00:00:00.000000', 'Thursday', 556.2)
('2008-09-03 00:00:00.000000', 'Wednesday', 950.25)
('2008-06-12 00:00:00.000000', 'Thursday', 1080.75)
('2010-04-16 00:00:00.000000', 'Friday', 767.55)
('2008-02-06 00:00:00.000000', 'Wednesday', 488.9)
('2011-10-19 00:00:00.000000', 'Wednesday', 662.3)
('2008-02-05 00:00:00.000000', 'Tuesday', 416.4)
('2008-02-04 00:00:00.000000', 'Monday', 306.2)
('2010-04-09 00:00:00.000000', 'Friday', 1294.95)
('2008-02-03 00:00:00.000000', 'Sunday', 888.15)
('2008-02-10 00:00:00.000000', 'Sunday', 526.75)
('2011-10-22 00:00:00.000000', 'Saturday', 1317.9)
('2008-02-09 00:00:00.000000', 'Saturday', 1111.1)
('2010-04-08 00:00:00.000000', 'Thursday', 769.85)
('2011-10-21 00:00:00.000000', 'Friday', 1142.6)
('2008-02-08 00:00:00.000000', 'Friday', 741.95)
('2008-02-07 00:00:00.000000', 'Thursday', 537.95)
('2010-04-11 00:00:00.000000', 'Sunday', 308.4)
('2012-01-06 00:00:00.000000', 'Friday', 740.75)
('2008-04-23 00:00:00.000000', 'Wednesday', 621.4)
('2010-04-10 00:00:00.000000', 'Saturday', 642.35)
('2012-01-07 00:00:00.000000', 'Saturday', 925.85)
('2008-04-24 00:00:00.000000', 'Thursday', 627.08)
('2010-04-13 00:00:00.000000', 'Tuesday', 479.85)
('2008-04-25 00:00:00.000000', 'Friday', 1189.0)
('2012-01-08 00:00:00.000000', 'Sunday', 377.95)
('2008-04-26 00:00:00.000000', 'Saturday', 1621.25)
('2010-04-12 00:00:00.000000', 'Monday', 318.7)
('2008-04-27 00:00:00.000000', 'Sunday', 1221.75)
('2012-01-09 00:00:00.000000', 'Monday', 435.55)
('2010-04-15 00:00:00.000000', 'Thursday', 559.25)
('2008-04-28 00:00:00.000000', 'Monday', 693.5)
('2012-01-10 00:00:00.000000', 'Tuesday', 292.7)
('2010-04-14 00:00:00.000000', 'Wednesday', 344.6)
('2008-04-29 00:00:00.000000', 'Tuesday', 528.45)
('2008-04-30 00:00:00.000000', 'Wednesday', 852.7)
('2010-08-25 00:00:00.000000', 'Wednesday', 820.85)
('2008-10-09 00:00:00.000000', 'Thursday', 614.85)
('2010-04-21 00:00:00.000000', 'Wednesday', 311.35)
('2012-01-11 00:00:00.000000', 'Wednesday', 433.65)
('2010-08-26 00:00:00.000000', 'Thursday', 620.55)
('2012-01-04 00:00:00.000000', 'Wednesday', 465.4)
('2008-10-08 00:00:00.000000', 'Wednesday', 744.75)
('2010-08-27 00:00:00.000000', 'Friday', 804.8)
('2012-03-12 00:00:00.000000', 'Monday', 257.9)
('2008-10-05 00:00:00.000000', 'Sunday', 685.0)
('2012-03-22 00:00:00.000000', 'Thursday', 668.3)
('2008-10-04 00:00:00.000000', 'Saturday', 942.75)
('2010-08-28 00:00:00.000000', 'Saturday', 918.75)
('2012-01-05 00:00:00.000000', 'Thursday', 332.9)
('2008-10-07 00:00:00.000000', 'Tuesday', 527.6)
('2012-03-23 00:00:00.000000', 'Friday', 711.95)
('2010-08-29 00:00:00.000000', 'Sunday', 925.1)
('2008-10-06 00:00:00.000000', 'Monday', 477.5)
('2008-10-01 00:00:00.000000', 'Wednesday', 500.25)
('2012-01-21 00:00:00.000000', 'Saturday', 617.5)
('2010-08-30 00:00:00.000000', 'Monday', 540.95)
('2008-09-30 00:00:00.000000', 'Tuesday', 521.6)
('2012-01-20 00:00:00.000000', 'Friday', 362.45)
('2010-08-31 00:00:00.000000', 'Tuesday', 528.05)
('2012-01-19 00:00:00.000000', 'Thursday', 120.0)
('2008-10-03 00:00:00.000000', 'Friday', 771.25)
('2010-09-01 00:00:00.000000', 'Wednesday', 1190.25)
('2012-01-18 00:00:00.000000', 'Wednesday', 176.75)
('2010-09-02 00:00:00.000000', 'Thursday', 793.65)
('2008-10-02 00:00:00.000000', 'Thursday', 309.6)
('2012-01-17 00:00:00.000000', 'Tuesday', 259.7)
('2010-09-03 00:00:00.000000', 'Friday', 960.7)
('2008-07-03 00:00:00.000000', 'Thursday', 719.75)
('2012-01-16 00:00:00.000000', 'Monday', 383.5)
('2009-03-23 00:00:00.000000', 'Monday', 692.25)
('2010-09-04 00:00:00.000000', 'Saturday', 921.7)
('2012-01-15 00:00:00.000000', 'Sunday', 632.65)
('2008-06-21 00:00:00.000000', 'Saturday', 1477.95)
('2009-03-22 00:00:00.000000', 'Sunday', 644.38)
('2011-03-24 00:00:00.000000', 'Thursday', 299.85)
('2008-06-20 00:00:00.000000', 'Friday', 1651.75)
('2012-01-14 00:00:00.000000', 'Saturday', 555.95)
('2009-03-21 00:00:00.000000', 'Saturday', 737.3)
('2010-04-26 00:00:00.000000', 'Monday', 276.15)
('2007-11-19 00:00:00.000000', 'Monday', 257.75)
('2012-03-09 00:00:00.000000', 'Friday', 1031.85)
('2009-03-20 00:00:00.000000', 'Friday', 928.25)
('2012-01-23 00:00:00.000000', 'Monday', 242.4)
('2007-11-20 00:00:00.000000', 'Tuesday', 355.75)
('2010-04-27 00:00:00.000000', 'Tuesday', 306.2)
('2012-01-22 00:00:00.000000', 'Sunday', 165.25)
('2009-03-19 00:00:00.000000', 'Thursday', 797.75)
('2011-06-11 00:00:00.000000', 'Saturday', 1070.95)
('2007-11-13 00:00:00.000000', 'Tuesday', 542.0)
('2012-03-20 00:00:00.000000', 'Tuesday', 412.45)
('2007-11-14 00:00:00.000000', 'Wednesday', 430.0)
('2009-03-18 00:00:00.000000', 'Wednesday', 728.25)
('2011-06-10 00:00:00.000000', 'Friday', 1271.05)
('2007-11-11 00:00:00.000000', 'Sunday', 507.0)
('2012-03-21 00:00:00.000000', 'Wednesday', 608.2)
('2009-03-17 00:00:00.000000', 'Tuesday', 620.25)
('2011-06-09 00:00:00.000000', 'Thursday', 1128.2)
('2007-11-12 00:00:00.000000', 'Monday', 399.0)
('2012-03-18 00:00:00.000000', 'Sunday', 584.5)
('2011-06-08 00:00:00.000000', 'Wednesday', 755.35)
('2009-03-16 00:00:00.000000', 'Monday', 443.25)
('2007-11-17 00:00:00.000000', 'Saturday', 612.75)
('2011-06-07 00:00:00.000000', 'Tuesday', 720.1)
('2012-02-10 00:00:00.000000', 'Friday', 495.2)
('2009-03-15 00:00:00.000000', 'Sunday', 393.5)
('2007-11-18 00:00:00.000000', 'Sunday', 527.75)
('2009-03-14 00:00:00.000000', 'Saturday', 755.0)
('2011-06-06 00:00:00.000000', 'Monday', 449.95)
('2011-10-11 00:00:00.000000', 'Tuesday', 533.9)
('2007-11-15 00:00:00.000000', 'Thursday', 416.0)
('2011-06-05 00:00:00.000000', 'Sunday', 648.95)
('2009-05-05 00:00:00.000000', 'Tuesday', 687.0)
('2007-11-16 00:00:00.000000', 'Friday', 489.75)
('2011-10-12 00:00:00.000000', 'Wednesday', 872.45)
('2008-05-26 00:00:00.000000', 'Monday', 768.5)
('2012-03-14 00:00:00.000000', 'Wednesday', 233.5)
('2011-06-04 00:00:00.000000', 'Saturday', 693.9)
('2009-05-06 00:00:00.000000', 'Wednesday', 447.0)
('2009-05-03 00:00:00.000000', 'Sunday', 696.25)
('2009-05-04 00:00:00.000000', 'Monday', 348.25)
('2008-05-25 00:00:00.000000', 'Sunday', 939.25)
('2012-03-15 00:00:00.000000', 'Thursday', 348.75)
('2011-07-24 00:00:00.000000', 'Sunday', 1088.0)
('2009-05-09 00:00:00.000000', 'Saturday', 1300.04)
('2008-05-24 00:00:00.000000', 'Saturday', 786.5)
('2011-10-07 00:00:00.000000', 'Friday', 1164.7)
('2011-06-13 00:00:00.000000', 'Monday', 849.55)
('2008-05-23 00:00:00.000000', 'Friday', 883.7)
('2009-05-10 00:00:00.000000', 'Sunday', 1490.5)
('2011-10-08 00:00:00.000000', 'Saturday', 1039.7)
('2011-06-12 00:00:00.000000', 'Sunday', 1035.9)
('2008-05-30 00:00:00.000000', 'Friday', 1080.45)
('2010-12-17 00:00:00.000000', 'Friday', 300.6)
('2009-05-07 00:00:00.000000', 'Thursday', 918.75)
('2011-10-09 00:00:00.000000', 'Sunday', 1049.3)
('2010-12-18 00:00:00.000000', 'Saturday', 380.35)
('2008-05-29 00:00:00.000000', 'Thursday', 1004.42)
('2010-12-15 00:00:00.000000', 'Wednesday', 357.4)
('2009-05-08 00:00:00.000000', 'Friday', 1321.25)
('2008-05-28 00:00:00.000000', 'Wednesday', 598.5)
('2011-10-10 00:00:00.000000', 'Monday', 349.0)
('2010-12-16 00:00:00.000000', 'Thursday', 405.9)
('2009-05-11 00:00:00.000000', 'Monday', 797.5)
('2008-05-27 00:00:00.000000', 'Tuesday', 567.5)
('2011-10-03 00:00:00.000000', 'Monday', 182.2)
('2010-12-21 00:00:00.000000', 'Tuesday', 433.2)
('2009-05-12 00:00:00.000000', 'Tuesday', 637.5)
('2011-10-04 00:00:00.000000', 'Tuesday', 344.7)
('2010-12-22 00:00:00.000000', 'Wednesday', 331.35)
('2008-06-01 00:00:00.000000', 'Sunday', 1042.0)
('2008-11-15 00:00:00.000000', 'Saturday', 1020.5)
('2011-10-05 00:00:00.000000', 'Wednesday', 269.1)
('2008-05-31 00:00:00.000000', 'Saturday', 1250.8)
('2010-12-19 00:00:00.000000', 'Sunday', 486.4)
('2008-11-16 00:00:00.000000', 'Sunday', 639.25)
('2011-10-06 00:00:00.000000', 'Thursday', 358.75)
('2010-12-20 00:00:00.000000', 'Monday', 333.95)
('2008-08-22 00:00:00.000000', 'Friday', 954.75)
('2008-11-13 00:00:00.000000', 'Thursday', 393.25)
('2012-02-12 00:00:00.000000', 'Sunday', 591.7)
('2011-03-11 00:00:00.000000', 'Friday', 652.35)
('2008-08-21 00:00:00.000000', 'Thursday', 1065.7)
('2008-11-14 00:00:00.000000', 'Friday', 669.25)
('2011-03-10 00:00:00.000000', 'Thursday', 342.45)
('2008-08-24 00:00:00.000000', 'Sunday', 770.0)
('2012-02-11 00:00:00.000000', 'Saturday', 833.0)
('2008-11-19 00:00:00.000000', 'Wednesday', 312.25)
('2010-12-23 00:00:00.000000', 'Thursday', 483.2)
('2008-02-25 00:00:00.000000', 'Monday', 381.0)
('2011-12-15 00:00:00.000000', 'Thursday', 347.7)
('2008-11-20 00:00:00.000000', 'Thursday', 334.0)
('2010-12-24 00:00:00.000000', 'Friday', 431.1)
('2008-11-17 00:00:00.000000', 'Monday', 408.25)
('2008-08-26 00:00:00.000000', 'Tuesday', 889.25)
('2011-12-16 00:00:00.000000', 'Friday', 589.95)
('2011-03-07 00:00:00.000000', 'Monday', 286.35)
('2008-08-25 00:00:00.000000', 'Monday', 927.0)
('2008-11-18 00:00:00.000000', 'Tuesday', 287.25)
('2011-12-13 00:00:00.000000', 'Tuesday', 240.25)
('2011-03-06 00:00:00.000000', 'Sunday', 255.8)
('2008-11-21 00:00:00.000000', 'Friday', 600.25)
('2011-12-14 00:00:00.000000', 'Wednesday', 368.7)
('2011-03-09 00:00:00.000000', 'Wednesday', 535.9)
('2008-08-28 00:00:00.000000', 'Thursday', 917.0)
('2008-11-22 00:00:00.000000', 'Saturday', 640.25)
('2011-12-19 00:00:00.000000', 'Monday', 295.15)
('2011-03-08 00:00:00.000000', 'Tuesday', 383.3)
('2011-12-20 00:00:00.000000', 'Tuesday', 360.7)
('2010-03-07 00:00:00.000000', 'Sunday', 1095.95)
('2010-08-05 00:00:00.000000', 'Thursday', 601.2)
('2008-08-27 00:00:00.000000', 'Wednesday', 861.5)
('2010-03-08 00:00:00.000000', 'Monday', 406.55)
('2010-08-04 00:00:00.000000', 'Wednesday', 623.05)
('2011-12-17 00:00:00.000000', 'Saturday', 444.45)
('2008-08-30 00:00:00.000000', 'Saturday', 1106.7)
('2009-09-11 00:00:00.000000', 'Friday', 1071.5)
('2008-08-29 00:00:00.000000', 'Friday', 905.75)
('2010-07-28 00:00:00.000000', 'Wednesday', 627.4)
('2011-12-18 00:00:00.000000', 'Sunday', 316.95)
('2012-03-11 00:00:00.000000', 'Sunday', 702.15)
('2010-07-27 00:00:00.000000', 'Tuesday', 497.1)
('2008-03-21 00:00:00.000000', 'Friday', 1055.25)
('2009-09-10 00:00:00.000000', 'Thursday', 710.75)
('2011-12-21 00:00:00.000000', 'Wednesday', 410.15)
('2009-07-23 00:00:00.000000', 'Thursday', 716.75)
('2008-03-20 00:00:00.000000', 'Thursday', 646.2)
('2010-07-30 00:00:00.000000', 'Friday', 899.15)
('2010-07-29 00:00:00.000000', 'Thursday', 514.6)
('2011-12-22 00:00:00.000000', 'Thursday', 449.2)
('2008-03-19 00:00:00.000000', 'Wednesday', 464.55)
('2010-08-01 00:00:00.000000', 'Sunday', 741.6)
('2009-07-22 00:00:00.000000', 'Wednesday', 766.5)
('2008-03-18 00:00:00.000000', 'Tuesday', 460.75)
('2010-07-31 00:00:00.000000', 'Saturday', 1133.6)
('2012-03-06 00:00:00.000000', 'Tuesday', 380.95)
('2008-03-17 00:00:00.000000', 'Monday', 538.2)
('2009-07-25 00:00:00.000000', 'Saturday', 1014.5)
('2009-07-24 00:00:00.000000', 'Friday', 931.25)
('2008-03-16 00:00:00.000000', 'Sunday', 830.95)
('2012-01-03 00:00:00.000000', 'Tuesday', 371.65)
('2010-08-03 00:00:00.000000', 'Tuesday', 632.0)
('2011-10-02 00:00:00.000000', 'Sunday', 783.9)
('2010-08-02 00:00:00.000000', 'Monday', 624.9)
('2008-03-15 00:00:00.000000', 'Saturday', 929.5)
('2009-07-27 00:00:00.000000', 'Monday', 820.75)
('2011-10-01 00:00:00.000000', 'Saturday', 1017.7)
('2011-07-18 00:00:00.000000', 'Monday', 802.75)
('2008-03-14 00:00:00.000000', 'Friday', 704.45)
('2009-07-26 00:00:00.000000', 'Sunday', 1054.5)
('2011-07-17 00:00:00.000000', 'Sunday', 1416.57)
('2009-07-29 00:00:00.000000', 'Wednesday', 865.5)
('2008-09-29 00:00:00.000000', 'Monday', 515.25)
('2012-03-05 00:00:00.000000', 'Monday', 477.65)
('2009-07-28 00:00:00.000000', 'Tuesday', 666.0)
('2008-09-08 00:00:00.000000', 'Monday', 349.25)
('2010-05-23 00:00:00.000000', 'Sunday', 1037.15)
('2012-03-04 00:00:00.000000', 'Sunday', 1253.25)
('2009-07-31 00:00:00.000000', 'Friday', 1003.0)
('2008-09-09 00:00:00.000000', 'Tuesday', 337.25)
('2010-05-22 00:00:00.000000', 'Saturday', 839.0)
('2009-07-30 00:00:00.000000', 'Thursday', 710.5)
('2012-03-07 00:00:00.000000', 'Wednesday', 414.25)
('2008-03-23 00:00:00.000000', 'Sunday', 1025.95)
('2010-05-25 00:00:00.000000', 'Tuesday', 178.4)
('2009-12-24 00:00:00.000000', 'Thursday', 462.55)
('2008-03-22 00:00:00.000000', 'Saturday', 1129.6)
('2012-01-02 00:00:00.000000', 'Monday', 626.1)
('2009-12-26 00:00:00.000000', 'Saturday', 288.32)
('2008-09-26 00:00:00.000000', 'Friday', 826.75)
('2010-05-24 00:00:00.000000', 'Monday', 511.9)
('2011-09-26 00:00:00.000000', 'Monday', 533.8)
('2009-12-22 00:00:00.000000', 'Tuesday', 597.95)
('2011-09-25 00:00:00.000000', 'Sunday', 478.65)
('2008-09-27 00:00:00.000000', 'Saturday', 1003.25)
('2010-10-13 00:00:00.000000', 'Wednesday', 630.55)
('2009-09-19 00:00:00.000000', 'Saturday', 1179.25)
('2011-09-24 00:00:00.000000', 'Saturday', 1051.75)
('2010-10-14 00:00:00.000000', 'Thursday', 589.3)
('2008-09-25 00:00:00.000000', 'Thursday', 699.75)
('2011-09-23 00:00:00.000000', 'Friday', 1198.95)
('2009-12-20 00:00:00.000000', 'Sunday', 381.9)
('2008-09-23 00:00:00.000000', 'Tuesday', 772.0)
('2011-09-30 00:00:00.000000', 'Friday', 877.8)
('2010-05-21 00:00:00.000000', 'Friday', 767.4)
('2009-12-21 00:00:00.000000', 'Monday', 301.15)
('2011-09-29 00:00:00.000000', 'Thursday', 517.5)
('2010-05-20 00:00:00.000000', 'Thursday', 691.7)
('2007-06-19 00:00:00.000000', 'Tuesday', 815.0)
('2010-10-09 00:00:00.000000', 'Saturday', 1144.45)
('2009-06-06 00:00:00.000000', 'Saturday', 1162.75)
('2011-09-28 00:00:00.000000', 'Wednesday', 939.85)
('2007-09-09 00:00:00.000000', 'Sunday', 806.5)
('2009-06-07 00:00:00.000000', 'Sunday', 1249.75)
('2011-09-27 00:00:00.000000', 'Tuesday', 717.35)
('2010-10-10 00:00:00.000000', 'Sunday', 569.55)
('2007-09-08 00:00:00.000000', 'Saturday', 970.75)
('2012-02-09 00:00:00.000000', 'Thursday', 405.6)
('2009-06-08 00:00:00.000000', 'Monday', 604.5)
('2010-10-11 00:00:00.000000', 'Monday', 753.95)
('2010-10-12 00:00:00.000000', 'Tuesday', 647.65)
('2009-06-09 00:00:00.000000', 'Tuesday', 529.25)
('2007-09-07 00:00:00.000000', 'Friday', 821.25)
('2012-03-10 00:00:00.000000', 'Saturday', 770.15)
('2010-10-05 00:00:00.000000', 'Tuesday', 413.35)
('2007-09-06 00:00:00.000000', 'Thursday', 362.75)
('2012-02-03 00:00:00.000000', 'Friday', 770.6)
('2009-06-02 00:00:00.000000', 'Tuesday', 929.0)
('2010-10-06 00:00:00.000000', 'Wednesday', 557.15)
('2010-10-07 00:00:00.000000', 'Thursday', 515.1)
('2007-09-05 00:00:00.000000', 'Wednesday', 632.5)
('2010-10-08 00:00:00.000000', 'Friday', 1038.85)
('2011-12-24 00:00:00.000000', 'Saturday', 233.65)
('2009-06-03 00:00:00.000000', 'Wednesday', 685.25)
('2007-09-04 00:00:00.000000', 'Tuesday', 623.0)
('2011-05-03 00:00:00.000000', 'Tuesday', 732.1)
('2011-12-23 00:00:00.000000', 'Friday', 490.95)
('2009-06-04 00:00:00.000000', 'Thursday', 964.25)
('2007-09-03 00:00:00.000000', 'Monday', 808.25)
('2011-05-04 00:00:00.000000', 'Wednesday', 873.9)
('2009-06-05 00:00:00.000000', 'Friday', 1132.25)
('2011-12-27 00:00:00.000000', 'Tuesday', 305.65)

### Access the sample data as a Pandas DataFrame

In [5]:
df = nocisales.pandas()

In [7]:
df.sort_index()

           Day of Week    Sales
Date
2007-06-15      Friday   783.50
2007-06-16    Saturday  1214.75
2007-06-17      Sunday  1381.00
2007-06-18      Monday  1033.75
2007-06-19     Tuesday   815.00
2007-06-20   Wednesday   980.00
2007-06-21    Thursday  1242.50
2007-06-22      Friday  1514.00
2007-06-23    Saturday  1638.50
2007-06-24      Sunday  1806.50
2007-06-25      Monday   792.00
2007-06-26     Tuesday   852.00
2007-06-27   Wednesday  1139.25
2007-06-28    Thursday  1131.00
2007-06-29      Friday  1109.00
2007-06-30    Saturday  1147.50
2007-07-01      Sunday  1220.25
2007-07-02      Monday  1091.25
2007-07-03     Tuesday  1199.00
2007-07-04   Wednesday   420.75
2007-07-05    Thursday  1151.75
2007-07-06      Friday  1120.75
2007-07-07    Saturday  1448.00
2007-07-08      Sunday   909.50
2007-07-09      Monday   641.75
2007-07-10     Tuesday   583.00
2007-07-11   Wednesday   695.25
2007-07-12    Thursday   829.00
2007-07-13      Friday  1394.25
2007-07-14    Saturday  1513.00
...                ...      ...
2012-03-01    Thursday   398.25
2012-03-02      Friday   782.05
2012-03-03    Saturday  1089.40
2012-03-04      Sunday  1253.25
2012-03-05      Monday   477.65
2012-03-06     Tuesday   380.95
2012-03-07   Wednesday   414.25
2012-03-08    Thursday   721.35
2012-03-09      Friday  1031.85
2012-03-10    Saturday   770.15
2012-03-11      Sunday   702.15
2012-03-12      Monday   257.90
2012-03-13     Tuesday   137.25
2012-03-14   Wednesday   233.50
2012-03-15    Thursday   348.75
2012-03-16      Friday   435.65
2012-03-17    Saturday   636.35
2012-03-18      Sunday   584.50
2012-03-19      Monday   335.15
2012-03-20     Tuesday   412.45
2012-03-21   Wednesday   608.20
2012-03-22    Thursday   668.30
2012-03-23      Friday   711.95
2012-03-24    Saturday   206.75
2012-03-25      Sunday   496.20
2012-03-26      Monday   369.95
2012-03-27     Tuesday   258.95
2012-03-28   Wednesday   585.80
2012-03-29    Thursday   432.75
2012-03-30      Friday   659.55

[1727 rows x 2 columns]